openapi: 3.0.0
info:
  version: 1.0.0
  title: Custom Server API
  description: API between HSM Agent and custom client's server

servers:
  - url: https://localhost:5000/v1


paths:
  /txToSign:
    post:
      summary: Sign Transaction
      description: Sign Transaction
      responses:
        200:
          description: Transaction ACK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TxResponse'
        default:
          $ref: "#/components/schemas/Error"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TxRequest'
        description: Transaction to sign

components:
  schemas: 
    SignedTxResponse:
      type: object
      required:
        - txId
        - signedTx
      properties:
        txId:
          type: string
          format: uuid
          example: 8c2b2b3d-fb83-497e-8138-72446b9184b6
        signedTx:
          type: string
    TxRequest:
      type: object
      required:
        - txId
        - keyId
        - payload
        - algorithm
      properties:
        txId:
          type: string
          format: uuid
          example: 8c2b2b3d-fb83-497e-8138-72446b9184b6
        keyId:
          description: keyId that is associated with the HSM private key
          type: string
          format: uuid
          example: 0ba9efb7-73cc-4ea5-9219-2aed45b06364
        payload:
          description: payload to sign
          type: string
          example: dc93a3b504f2ede4e03e60758571be627b2512aafa1c5e21db4c6b88d0813e9e
        algorithm:
          description: algorithm to sign with
          type: string
          enum: [ECDSA, EDDSA]
          example: ECDSA
    TxResponse:
      type: object
      required:
        - txId
      properties:
        txId:
          type: string
          format: uuid
          example: 8c2b2b3d-fb83-497e-8138-72446b9184b6
    Error:
      type: object
      required:
          - code
          - message
      properties:
        message:
          type: string

