openapi: 3.0.0
info:
  version: 1.0.0
  title: Custom Server API
  description: API between HSM Agent and custom client's server

servers:
  - url: https://localhost:5000/v1


paths:
  /messagesStatus:
    post:
      summary: Get updates on requested messages
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessagesStatusRequest'
      responses:
        200:
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/MessagesStatusResponse'
  /messagesToSign:
    post:
      summary: Sign Messages
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessagesRequest'
        description: Messages to sign
      responses:
        200:
          description: Messages Status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessagesStatusResponse'
        default:
          $ref: "#/components/schemas/Error"

components:
  schemas: 
    MessagesStatusRequest:
      type: object
      required:
        - msgIds
      properties:
        msgIds:
          type: array
          items:
            type: string
            format: uuid
            example: 8c2b2b3d-fb83-497e-8138-72446b9184b6
    MessagesStatusResponse:
      type: object
      required:
        - messages
      properties:
        messages:
          type: array
          items:
            $ref: '#/components/schemas/MessageStatus'
    MessagesRequest:
      type: object
      required:
        - messages
      properties:
        messages:
          type: array
          items:
            $ref: '#/components/schemas/MessageEnvelope'
    MessageEnvelope:
      type: object
      required:
        - msgId
        - message
      properties:
        msgId:
          type: string
          format: uuid
          example: 9eca83b5-5936-4eef-89cc-51bec0f49945
        message:
          $ref: '#/components/schemas/Message'
    MessageStatus:
      type: object
      required:
        - msgId
        - txId
        - status
      properties:
        msgId:
          type: string
          format: uuid
          example: 8c2b2b3d-fb83-497e-8138-72446b9184b6
        txId:
          type: string
          format: uuid
          example: 8c2b2b3d-fb83-497e-8138-72446b9184b6
        status:
          type: string
          enum: [PENDING_SIGN, SIGNED, FAILED]
          example: ECDSA
        errorMessage:
          type: string
          exmaple: Transction 8c2b2b3d-fb83-497e-8138-72446b9184b6 failed due to insufficient funds
        payload:
          type: string
          exmaple: singed-tx-string
    Message:
      type: object
      required:
        - txId
        - keyId
        - payload
        - algorithm
      properties:
        txId:
          type: string
          format: uuid
          example: 8c2b2b3d-fb83-497e-8138-72446b9184b6
        keyId:
          description: keyId that is associated with the HSM private key
          type: string
          format: uuid
          example: 0ba9efb7-73cc-4ea5-9219-2aed45b06364
        payload:
          description: payload to sign
          type: string
          example: dc93a3b504f2ede4e03e60758571be627b2512aafa1c5e21db4c6b88d0813e9e
        algorithm:
          description: algorithm to sign with
          type: string
          enum: [ECDSA, EDDSA]
          example: ECDSA
    Error:
      type: object
      required:
          - code
          - message
      properties:
        message:
          type: string

